PROG = bin/dwmblocks-fast

CC = cc

$(PROG): objs.mk $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(LDFLAGS) $(CPPFLAGS)

clean:
	rm -f src/*.o src/*/*.o bin/*

objs.mk: objs-build.mk

objs-build.mk: Makefile.base config.mk src/* src/*/* include/* include/*/*
	./build-make
