#!/bin/sh
[ -n "$1" ] || exit 1
out_dir=$1
sigs=$(grep 'define SIG_' ./src/config.h | sed 's/.*define.*\(SIG_[A-Z]*\)[ \t]*\([0-9]*\)/\1=\2/')
shift
for file in $@; do
	{
	out_file="$out_dir/$(basename $file)"
	echo "#!/bin/sh" >"$out_file"
	echo "$sigs" >>"$out_file"
	grep -v '^#!/bin/sh$\|^SIG_' "$file" >>"$out_file"
	} &
done
wait
