#!/bin/sh
# Add mutex?
i=$1
[ -z $1 ] && i=1
pamixer -i "$i"
killall dwmblocks-fast
nohup dwmblocks-fast >/dev/null &
if [ $(ps -e -o comm --no-headers | grep -Fc -e 'gst-play-1.0') -le 2 ]; then
	# ffplay seems to sound worse
	# ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
	gst-play-1.0 -q /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
fi
