#!/bin/sh
pamixer -t
killall dwmblocks-fast
nohup dwmblocks-fast >/dev/null &
# ffplay -nodisp -autoexit /usr/share/sounds/freedesktop/stereo/bell.oga &
gst-play-1.0 -q /usr/share/sounds/freedesktop/stereo/bell.oga &
if [ $(dwmblocks-fast-mic-ismuted) = 'true' ]; then
	notif='🔇 Speaker is muted!'
else
	notif='🔉 Speaker is on!'
fi
dunstctl close
notify-send "$notif"
