#!/bin/sh
dunstctl close
if sudo modprobe uvcvideo; then
	notify-send "📷 webcam is turned on! 🟢"
else
	notify-send "🔴📷 Error: can not turn on webcam!"
fi
killall dwmblocks-fast
nohup dwmblocks-fast >/dev/null &
gst-play-1.0 -q /usr/share/sounds/freedesktop/stereo/device-added.oga &
