#!/bin/sh
dunstctl close
if sudo modprobe uvcvideo; then
	notify-send "📷 webcam is turned on! 🟢"
else
	notify-send "🔴📷 Error: can not turn on webcam!"
fi
nice -n 19 gst-play-1.0 -q /usr/share/sounds/freedesktop/stereo/device-added.oga &
pkill -RTMIN+"$SIG_WEBCAM" dwmblocks-fast
